apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: istio-ef-debug
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: sample-application
  configPatches:
  - applyTo: HTTP_FILTER  # NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
    patch:
      operation: INSERT_BEFORE
      value:
        config:
          inlineCode: |
            function envoy_on_request(request_handle)
              request_handle:logInfo("******* Enter debug logs - envoy_on_request")
              local headers = request_handle:headers()
              for key,value in pairs(headers) do request_handle:logInfo(key.." "..value) end

              for chunk in request_handle:bodyChunks() do
                request_handle:logInfo(chunk:getBytes(0,chunk:length()))
              end
            
            
            function envoy_on_response(response_handle)
              response_handle:logInfo("******* Enter debug logs - envoy_on_response")
              local pheaders = response_handle:headers()
              for key,value in pairs(pheaders) do response_handle:logInfo(key.." "..value) end

              for chunk in response_handle:bodyChunks() do
                response_handle:logInfo(chunk:getBytes(0,chunk:length()))
              end

            end
        name: envoy.lua
